=== vdwtanner/Crusade/Final Src/img/Levelling.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Levelling" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Levelling">
<xsd:annotation>
<xsd:appinfo>
<od:tableProperty name="GUID" type="9" value="Ow3dnaGvCUqt1KRycOpiqg==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAA7Dd2doa8JSq3UpHJw6mKqAAAAAMl+A8CXquRAAAAAAAAAAABMAGUA
dgBlAGwAbABpAG4AZwAAAAAAAADtBWi86pBKSJ9F7eS1cpw1BwAAADsN3Z2hrwlK
rdSkcnDqYqpMAGUAdgBlAGwAAAAAAAAATbfF14gZiEmbNJrRAHshVAcAAAA7Dd2d
oa8JSq3UpHJw6mKqRQBYAFAAAAAAAAAA+/KqwQOJAUGoL9G7n6/fMgcAAAA7Dd2d
oa8JSq3UpHJw6mKqQQBiAGkAbABpAHQAaQBlAHMAAAAAAAAAr56FjBLpUEeO6u1Q
AggVogcAAAA7Dd2doa8JSq3UpHJw6mKqUABhAHMAcwBpAHYAZQBzAAAAAAAAAOkc
v5eeyqdGjtrxOOA+5CoHAAAAOw3dnaGvCUqt1KRycOpiqkgAUAAAAAAAAADkwDRu
5KR+TbF6u5OMFD8fBwAAADsN3Z2hrwlKrdSkcnDqYqpNAGEAbgBhAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAMAAAABQAAAAAAAAAAAAAAAAAAAAAA
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="100"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Level" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="7QVovOqQSkifRe3ktXKcNQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="EXP" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="TbfF14gZiEmbNJrRAHshVA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Abilities" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="+/KqwQOJAUGoL9G7n6/fMg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Passives" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="r56FjBLpUEeO6u1QAggVog==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="HP" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="6Ry/l57Kp0aO2vE44D7kKg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Mana" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="5MA0buSkfk2xeruTjBQ/Hw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ManaRegen" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== vdwtanner/Crusade/Final Src/img/Levelling.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Levelling.xsd" generated="2015-12-02T13:55:03">
<Levelling>
<Level>1</Level>
<EXP>0</EXP>
<Abilities>7</Abilities>
<HP>45</HP>
<Mana>5</Mana>
<ManaRegen>1</ManaRegen>
</Levelling>
<Levelling>
<Level>2</Level>
<EXP>150</EXP>
<Abilities>3</Abilities>
<HP>55</HP>
<Mana>15</Mana>
<ManaRegen>1</ManaRegen>
</Levelling>
<Levelling>
<Level>3</Level>
<EXP>450</EXP>
<Abilities>9</Abilities>
<HP>65</HP>
<Mana>25</Mana>
<ManaRegen>1</ManaRegen>
</Levelling>
<Levelling>
<Level>4</Level>
<EXP>1000</EXP>
<Abilities>1</Abilities>
<HP>70</HP>
<Mana>30</Mana>
<ManaRegen>2</ManaRegen>
</Levelling>
<Levelling>
<Level>5</Level>
<EXP>2250</EXP>
<HP>80</HP>
<Mana>40</Mana>
<ManaRegen>2</ManaRegen>
</Levelling>
<Levelling>
<Level>6</Level>
<EXP>3500</EXP>
<Abilities>4</Abilities>
<HP>85</HP>
<Mana>45</Mana>
<ManaRegen>2</ManaRegen>
</Levelling>
<Levelling>
<Level>7</Level>
<EXP>5000</EXP>
<HP>95</HP>
<Mana>55</Mana>
<ManaRegen>3</ManaRegen>
</Levelling>
<Levelling>
<Level>8</Level>
<EXP>6500</EXP>
<Passives>(4,1)</Passives>
<HP>100</HP>
<Mana>65</Mana>
<ManaRegen>3</ManaRegen>
</Levelling>
<Levelling>
<Level>9</Level>
<EXP>8500</EXP>
<HP>110</HP>
<Mana>75</Mana>
<ManaRegen>3</ManaRegen>
</Levelling>
<Levelling>
<Level>10</Level>
<EXP>11000</EXP>
<HP>120</HP>
<Mana>85</Mana>
<ManaRegen>4</ManaRegen>
</Levelling>
</dataroot>
